### PR TITLE
Bug in testing live cluster bug

### PR DESCRIPTION
**Pull request by tanyaveksler**
Added a delay after deploying resources in testing live cluster, to make sure all pods are up and running

### CODE REVIEW

**Comment by tanyaveksler** [comment]
Test_docker fails because gcc is missing - I remember you mentioned it in the project meeting, but I don't know how to workaround it.

**Review by zivnevo — DISMISSED** [review]
ok to merge.
For now ignore the test_docker failure - I'll fix it later. You should be able to merge with this fail.

**Comment by zivnevo** [comment]
I fixed the `test_docker` failure, Should be ok after you merge the latest changes from master.

**Comment by zivnevo** [comment]
Also, maybe it's time to sync `tests/fw_rules_tests/podlist/kubernetes-manifests.yaml` with its [origin](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/release/kubernetes-manifests.yaml), as it got a little bit old.

For example, our version specifies using adservice version v0.1.3 - but there is no longer such version on [Google's registry](https://console.cloud.google.com/gcr/images/google-samples/global/microservices-demo/adservice), so the pod keeps failing.

**Review by zivnevo — APPROVED** [review]
ok to merge

**Pull request merged**
